name: Update NPM Repository
on:
  release:
  types: [published]

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          persist-credentials: false

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          registry-url: https://registry.npmjs.org
      
      - name: Install Dependencies
        run: npm ci

      - name: Version App
        run: npm version patch

      - name: Commit New Version
        run: |
          git show
          git push

      - name: Publish to NPM
        run: echo "Under construction"