name: Update NPM Repository

on: workflow_dispatch

  # release:
  #   types: [created]

jobs: 
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          persist-credentials: false

      - name: Log Current Release
        run: echo "${{ github.ref_name }}"

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          registry-url: https://registry.npmjs.org
      
      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM
        run: echo "Under construction"

      - name: 'Change Version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '1.0.1'
          package: ''
          git-tag-version: 'true'

      - name: Version App
        run: npm version patch

      - uses: stefanzweifel/git-auto-commit-action@v4