name: Update NPM Repository

on: workflow_dispatch

  # release:
  #   types: [created]

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          persist-credentials: false

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          registry-url: https://registry.npmjs.org
      
      - name: Install Dependencies
        run: npm ci

      - name: Version App
        run: npm version patch

      - name: Commit New Version
        run: |
          git show
          git push

      - name: Publish to NPM
        run: echo "Under construction"